
server:
  port: 8082
spring:
  application:
    name: rocketmq-springboot-consumer
rocketmq:
  consumer:
    # 是否开启自动配置
    isOnOff: 'on'
    # 发送同一类消息设置为同一个group，保证唯一默认不需要设置，rocketmq会使用ip@pid（pid代表jvm名字）作为唯一标识
    groupName: 'test_group_consumer'
    # mq的nameserver地址
    namesrvAddr: '127.0.0.1:9876'
    topics: 'test_topic_user:tag02 || tag03;test_topic_order:*'
    # 消费者线程数据量最小
    consumeThreadMin: 5
    # 消费者线程数据量最大
    consumeThreadMax: 32
    #  设置一次消费信息的条数，默认1
    consumeMessageBatchMaxSize: 1


